print("Hello World!")
print("Hello Again")
print("This is funny?")
print("seems so!")
print("Then he said, is that so?")
print("Then came the 'error'")
print("right?")
print("I will be more than happy if things work the way I have understood Git")
print("It did not happen at my first time. Lets try once again @ 9:16") 
print("I performed it again, it happened")
